# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c225429ebcead103723f84e5e28b444d2d112c51760ba7f077f10b8912a06c93b728ba10f9c7a0121e86f3e3b942f5baa66989d3198a32ee079e17e202b5baf

test:
  secret_key_base: 6c75a9c36f2acd34b21ea01ebefa3101fa4766ea6eaa011de8ae7a35934bfb4baad895e4c186c875cc7efb0f07170f3ed5dacb78f2a1c050bb3db170d5b70107

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
